language: objective-c
osx_image: xcode8.0
env:
  - DESTINATION="OS=10.0,name=iPhone 7" SCHEME="SwiftValidate" SDK=iphonesimulator
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script: ./travis.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'SwiftValidate'
